### PR TITLE
Implement page rules

### PR DESCRIPTION
**Pull request by OJFord**
This PR is a rebasing of hashicorp/terraform#11249 due to the new (-ish, which is testament to how stale I let this get!) providers structure.

I'm working on tests right now, but (assuming no side-effect of the new structure)  it is currently functional by my manual tests.

Messrs. @thasmo @jamestyrrell @jonleighton @mwarkentin - you've expressed interest (either in hashicorp/terraform#9040 or in #3) of support for CloudFlare page rules; if you're able to verify this is working too that would be much appreciated :slightly_smiling_face:

N.B.
I retained the history from my branch in the core repo; an unfortunate side-effect of which is that Github seems to have a new (?) element for authors/committers which is listing my name twice. :laughing:

Presumably if this is merged I'll no longer be the committer, and so I would be listed only as the author, (OJFord + Maintainer)  so I'm tempted just to leave it as it is. If you'd prefer I clean it up though; I *think* it would just be a matter of rebasing with `--reset-author`.

**Note**: this isn't _quite_ ready to be merged, waiting for cloudflare/cloudflare-go#138 because the alternative is a nasty hack.

### CODE REVIEW

**Comment by mwarkentin** [comment]
@OJFord Thanks for this. I'd be happy to test out, but not sure how to test a WIP branch like this. :)

**Comment by OJFord** [comment]
@mwarkentin Thank you for offering, as it turns out neither am I! The new structure makes it easy to work on and build the provider plugin, but these aren't linked at run-time, and I'm still trying to build terraform core using it myself.

**Comment by OJFord** [comment]
OK, I've managed it, though it might be a bit of a tall order if you aren't already using go:

- Install golang, and be absolutely sure (!!) you've set `$GOPATH`, to e.g. `/home/you/go`, and that it's in your system `$PATH`
-  Clone my fork of this repo (or this repo, and add my remote) to `$GOPATH/src/github.com/terraform-providers/terraform-provider-cloudflare`
- Clone terraform core to  `[...]/hashicorp/terraform`
- `cd` into this repo, and `make build`
- `cd` into the core repo, and  `make  dev`

(It actually doesn't look so bad now that I've done it, and written it out... but approaching it for the first time without knowing much about go - nevermind its plugin system - was not a quick process. I thought from the core repo's documentation for example, that `make plugin-dev` was for community providers etc. - but it's for 'built-in plugins' contained within the core repo.)

Then you can create a test `.tf` that looks something like:
```hcl
provider "cloudflare" {
  email = "your.cf.login@email.com"
  token = "hunter2"
}

resource "cloudflare_page_rule" "foobar" {
  domain = "you.com"
  target = "sub.you.com"

  actions = {
    ssl = "flexible",
  }
```
and run `$GOPATH/bin/terraform plan && $GOPATH/bin/terraform apply`.

**Comment by OJFord** [comment]
Note: due to a (suspected, though it was previously accepted and believed fixed)  bug in the CF go library, `terraform apply` will give you an error about unmarshalling JSON. (c.f. CF issue linked above.)

However, if you check the CF web app, you *should* find that the rule has been successfully created/updated/deleted.

**Comment by mwarkentin** [comment]
@OJFord You may need to update the vendored cloudflare lib in terraform? I know that was something I had to do to pull in an update for a fix I added a while back.

**Comment by OJFord** [comment]
@mwarkentin  Ah, thanks for the pointer, though looking at the commit history there I can't see the fix at all - there's nothing from the date that @jamesog said it was fixed - and the only diffs to the `pagerules` package are comments.

Unless, (James) it was an API issue that was fixed and has regressed?

**Comment by bronislav** [comment]
Any updates? I would like to see it is merged soon :)

**Comment by OJFord** [comment]
@bronislav I'm afraid it's still blocked by cloudflare/cloudflare-go#138, I can work around it, but it's such a nasty hack (read all page rules, create a page rule, read all again and look at the diff to find the created object) with reliability issues that I assumed it wouldn't be merged anyway.

**Comment by bronislav** [comment]
@OJFord Got it.

**Comment by grubernaut** [comment]
Hey @OJFord, thanks for this! 

Feel free to ping me when this is ready to go, and I'll work on getting it added. 

Just as a note on provider development, as I saw you had some questions there: 

I usually do the same workflow for provider development in the post 0.10 provider-split world. Terraform will look for any providers named `terraform-provider-X` inside the same directory that the `terraform` binary exists. Thus, you only need to have the `terraform` binary installed to `$GOPATH/bin`, and run `make build` from the provider directory that you're developing from. 
With Terraform v0.10.0, you'll also have to run `terraform init` from your test configuration's directory, and again for each subsequent compilation of the provider, as Terraform verifies that the binary's SHASUM is the same inside of the environment. You can get around having to run `terraform init` each time you re-compile your provider by setting the `TF_SKIP_PROVIDER_VERIFY` environment variable to any non-nil string. 

Hope this helps! Please let us know if we can do anything to make this process better as well. (Would likely be better with a new issue on the Terraform repository for enhancements, so as not to pull focus from this PR).

**Comment by OJFord** [comment]
Just a note to say the upstream dependency cloudflare/cloudflare-go#138 has been picked up by @sublimedamien in cloudflare/cloudflare-go#154.

**Comment by dasch** [comment]
Any update on this?

**Comment by mwarkentin** [comment]
@dasch still blocked on the upstream library change, but there’s active development going on there. Hopefully it’ll land soon.

**Comment by benjvi** [comment]
@OJFord @dasch @mwarkentin  I've been doing some work on this recently. I needed to rebase on top of #32 which should solve the upstream API issues, then there were a few changes needed to get things working. It seemed a bit too fiddly to merge into this PR, so I've forked in #34 - which still needs review - but which is now functional in its current state

**Comment by OJFord** [comment]
Closed in favour of #34.

**Pull request closed without merging**
