### PR TITLE
forwarding_urls in page rules are lists

### PR DESCRIPTION
**Pull request by MrTravisB**
Currently when importing a page rule with a forwarding_url, the following error is given.

        2018-07-03T14:43:23.366-0700 [DEBUG] plugin.terraform-provider-cloudflare_v1.0.0_x4: 2018/07/03 14:43:23 [WARN] Error setting actions in page rule "XXXXXXXXXXXXXX": actions.0.forwarding_url: '': source data must be an array or slice, got map

This fixes that. forwarding_url is defined as a list and there needs to be set to a list.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
@MrTravisB Nice find. Is it possible to add (or expand on) a test case to prevent this from regressing?

**Comment by MrTravisB** [comment]
@jacobbednarz done

**Comment by patryk** [comment]
Indeed, good catch. Thanks Travis and thanks Jacob for taking time in reviewing it.

**Comment by jacobbednarz** [comment]
appreciate it @MrTravisB 🙇

**Pull request merged**
