### PR TITLE
Add firewall rule bypass and products supports

### PR DESCRIPTION
**Pull request by nadavshatz**
Dependent on https://github.com/cloudflare/cloudflare-go/pull/401

### CODE REVIEW

**Comment by nadavshatz** [comment]
Dependent has been merged. So this is ready :pray:

**Comment by jacobbednarz** [comment]
Not just yet. We need to cut a release upstream and have that pulled into this repository.

**Comment by nadavshatz** [comment]
Sounds good.  Looking forward. Cheers 🍻

**Comment by patryk** [comment]
Thanks @nadavshatz !

**Comment by nadavshatz** [comment]
No problem @patryk !

**Comment by nadavshatz** [comment]
@patryk any idea when a new release will be released? :)

**Comment by patryk** [comment]
We don't have any specific schedule, but usually it's monthly.

**Comment by jamesarosen** [comment]
> usually it's monthly.

It's now been about 6 weeks since this was merged. Is something holding up the release? This is a blocker for our configuration.

**Pull request merged**
