### PR TITLE
resource: page rule: Add support for cache key fields action

### PR DESCRIPTION
**Pull request by XaF**
Cache Key Fields action was not terraformable so far. This adds
the elements necessary to allow to define the Cache Key Fields
action in a page rule, along with the necessary documentation.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
Thanks for doing this @XaF but it looks like we've already got a PR for this one in #685. I'll have a chat with @patryk which way we want to go with this as while his PR is more verbose, it doesn't group the fields together in a way where value changes would require a big refactoring.

**Comment by XaF** [comment]
Oh well, seems that we've crossed beams!

**Comment by patryk** [comment]
That would be bad!

Well, I don't know what to do from this place. Maybe we could move your simplified transform code to my PR, because I'm not proud of large amount of type casting?

**Comment by XaF** [comment]
I'm good with anything you decide really! We just need that feature as we're terraforming a zone for which we want to configure the cache key fields, and I wrote this when I figured it wasn't supported yet, so as long as the feature becomes available soon I'm good! :)

If you want to take chunks of my code to put in your PR that works for me!

**Comment by patryk** [comment]
I have simplified the transform code, inspired by your PR here and merged. Thanks!

**Comment by XaF** [comment]
Thank you @patryk !

**Pull request closed without merging**
