### PR TITLE
Update to cloudflare-go 0.10.0

### LINKED ISSUE #227: Breaking changes for a major release
We've spoken a couple of times regarding cleaning up the Terraform interface or interactions which would result in breaking backwards compatibility. To discuss how we want to do this and how it will be executed, I've raised this issue. 

Here is a table from a quick search on the changes that we'd like to introduce:

Change | Discussion link | Reason
------------ | -------------| -------------
Swap `org_id` for `account_id` | https://github.com/terraform-providers/terraform-provider-cloudflare/pull/226#pullrequestreview-209887811 | Move off deprecated APIs and use newer nomenclature
Deprecate `zone_name` in favour of `zone_id` | https://github.com/terraform-providers/terraform-provider-cloudflare/issues/161#issuecomment-441128985 | More explicitness as domain name isn't unique but ID is.

I'll keep this table updated so if you have other things to add please pop them below and I'll update this accordingly.

Once we decide on what we want to change, I'll create a new milestone and we can start picking off the tasks to complete.

cc @patryk @garrettgalow @prdonahue

### PR DESCRIPTION
**Pull request by jacobbednarz**
Pulls in the deprecation of `Organization` in favour of `Account`.

Closes #227

### CODE REVIEW

**Comment by jacobbednarz** [comment]
Pending Hashicorp adding `CLOUDFLARE_ACCOUNT_ID` environment variable for the tests to run correctly.

**Comment by jacobbednarz** [comment]
CI environment variable added and suite is green.

**Comment by patryk** [comment]
Let's not rename fields yet, just update internal fields to accommodate breaking change in cloudflare-go. Let's put aside field renames for major version release.

**Comment by jacobbednarz** [comment]
@patryk this PR is intended to be that breaking change for the next major release 😛 Along with #417, this rounds out the changes we are doing for the next major release. I’ll also now need to remove the `zone` stuff too as you’ve merged that one.

**Comment by jacobbednarz** [comment]
I've updated these to use the base branch of v2.0 so that we can test all of these changes together on a single branch and then just merge that one instead of managing merge conflicts all over the place.

**Pull request merged**
