### PR TITLE
Adding import method for importing cloudflare_record resources

### LINKED ISSUE #5: Cloudflare record import support
_This issue was originally opened by @mwarkentin as hashicorp/terraform#11219. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version

 All.

### Affected Resource(s)

Please list the resources as a list, for example:
- [`cloudflare_record`](https://www.terraform.io/docs/providers/cloudflare/r/record.html)

### Expected Behavior

Terraform supports import of existing cloudflare records into state.

### Important Factoids

Need to determine how the record would be referenced:

* Record ID
* Full DNS name (may be ambiguous as you could have multiple types of records for the same domain)

### References

First reported in hashicorp/terraform#3715 but closed as `terraform import` wasn't a thing.

### PR DESCRIPTION
**Pull request by fillup**
Resolves #5 

Since Cloudflare API requires Zone ID to fetch record information, this import method will get a list of Zones first and foreach zone check if the given record ID exists and if so, import it. 

Here is example output of running a `plan`, then `apply`, getting an error about existing, then `import` and `plan` again to see that no changes are needed.

```
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

The Terraform execution plan has been generated and is shown below.
Resources are shown in alphabetical order for quick scanning. Green resources
will be created (or destroyed and then created if an existing resource
exists), yellow resources are being changed in-place, and red resources
will be destroyed. Cyan entries are data sources to be read.

Note: You didn't specify an "-out" parameter to save this plan, so when
"apply" is called, Terraform can't guarantee this is what will execute.

+ cloudflare_record.testdns
    domain:   "example.com"
    hostname: "<computed>"
    name:     "subdomain"
    proxied:  "true"
    ttl:      "<computed>"
    type:     "CNAME"
    value:    "otherdomain.com"
    zone_id:  "<computed>"


Plan: 1 to add, 0 to change, 0 to destroy.

$ terraform apply
cloudflare_record.testdns: Creating...
  domain:   "" => "example.com"
  hostname: "" => "<computed>"
  name:     "" => "subdomain"
  proxied:  "" => "true"
  ttl:      "" => "<computed>"
  type:     "" => "CNAME"
  value:    "" => "otherdomain.com"
  zone_id:  "" => "<computed>"

Error applying plan:

1 error(s) occurred:

* cloudflare_record.testdns: 1 error(s) occurred:

* cloudflare_record.testdns: Failed to create record: error from makeRequest: HTTP status 400: content "{\"success\":false,\"errors\":[{\"code\":81053,\"message\":\"An A, AAAA or CNAME record already exists with that host.\"}],\"messages\":[],\"result\":null}"

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

$ terraform import cloudflare_record.testdns 5937db7bdf76cf81014278b818680284
cloudflare_record.testdns: Importing from ID "5937db7bdf76cf81014278b818680284"...
cloudflare_record.testdns: Import complete!
  Imported cloudflare_record (ID: 5937db7bdf76cf81014278b818680284)
cloudflare_record.testdns: Refreshing state... (ID: 5937db7bdf76cf81014278b818680284)

Import success! The resources imported are shown above. These are
now in your Terraform state. Import does not currently generate
configuration, so you must do this next. If you do not create configuration
for the above resources, then the next `terraform plan` will mark
them for destruction.

$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

cloudflare_record.testdns: Refreshing state... (ID: 5937db7bdf76cf81014278b818680284)
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, Terraform
doesn't need to do anything.
```

I'll add that initially I wrote this to support importing using the actual hostname, such as terraform `import cloudflare_resource.testdns subdomain.example.com` but found the resource object's ID was fixed to `subdomain.example.com` and I could not change it to the actual ID, so the subsequent `Read` call failed. So if there is a way to change the ID in the Import function that could make the experience of importing records much better.

### CODE REVIEW

**Comment by bronislav** [comment]
@wcjr, @radeksimko Do you know when it will be released?

**Comment by wcjr** [comment]
@fillup will know

**Comment by fillup** [comment]
I wish I knew, but thats up to @radeksimko. I thought the intention of separating out the providers from the core Terraform repo was to accelerate enhancement of providers without bundling to core Terraform, but so far I'm not seeing that.

@radeksimko can you review this and either approve/merge or reject it? It's been open six months so its probably time to resolve it.

**Comment by rafilkmp3** [comment]
why this isn't merged yet ?

**Comment by fillup** [comment]
@radeksimko we talked about this in person at HashiConf. Is there any more information or discussion needed before it can be merged? Is there a reason to delay such as new features coming to Terraform that will allow for a more elegant solution?

**Comment by rafilkmp3** [comment]
I had to manually edit my tfstate in s3 to able to use again.

**Comment by lczxpplnzeey** [comment]
@fillup 

Question on the import command

terraform import cloudflare_record.testdns 5937db7bdf76cf81014278b818680284

testdns, i take it would be the resource name in terraform.

What's the 5937db7bdf76cf81014278b818680284?  is that DNS record ID in cloudflare?  How do you get that?

Lastly, I might be misreading but has the import issue been fixed and merged yet?

Thanks.

**Comment by fillup** [comment]
@lczxpplnzeey yes, that is the record ID. Unfortunately that value is not made available in the Cloudflare UI so I had to use the Cloudflare API to list my records and get their IDs. 

Originally I wrote the import to use the dns hostname, but that created other problems internally to Terraform that I could not work around. I talked to @radeksimko about it at HashiConf and he was going to look into it but I haven't heard any more about it.

**Comment by lczxpplnzeey** [comment]
@fillup That's a shame, cloudflare import is the only thorn in the side.  As we can't make any changes with it using terraform, unless we delete and recreate them in terraform.

But thanks, I was able to find the record ID.  Tried it and as expected, import isn't supported.

**Comment by fillup** [comment]
@lczxpplnzeey it is janky, but you could use the code from this PR to import them to get them into your statefile and then go back to standard distribution for further maintenance.

**Comment by lczxpplnzeey** [comment]
@fillup 

Total noob to this.

How do I clone your PR? And after I clone it, how to compile it?  

Also, would this be the cloudflare plugin or terraform executable? or both?

**Comment by rafilkmp3** [comment]
we have plans to have this merged ?

**Comment by greut** [comment]
:+1: I've tested it on top of #32

**Comment by benjvi** [comment]
@fillup I would suggest that its better to specify the zone as part of the import id, then set it during the Import method, this way, you can avoid having to iterate through the zones. This is the approach I've used here: https://github.com/benjvi/terraform-provider-cloudflare/blob/page-rules-continued/cloudflare/resource_cloudflare_page_rule.go#L481 . Does that approach look good to you?

Also it seems to be more idiomatic to just set the values that are not set during 'Read' since terraform will always run read anyway.

I should have some time on Monday to make the changes required, let me know in case you have any time to spend with this.

 Hopefully some of these PRs will be getting some TLC from a maintainer quite soon

**Comment by aexmachina** [comment]
Should this PR be closed in favour of #36?

**Comment by patryk** [comment]
Yes, I think so. Thanks Simon!

**Pull request closed without merging**
