### PR TITLE
cloudflare_zone: add verification_key attribute for partial zones

### PR DESCRIPTION
**Pull request by inge4pres**
Hi

here I address an addition to fix a corollary of #280.
Because this change also depends on a PR not yet merged on `cloudflare-go` (https://github.com/cloudflare/cloudflare-go/pull/355) I had to `replace` in the `go.mod` the dependency with the forked repo.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
Are you able to please remove the go.mod additions and we’ll mark this as blocked on dependencies? 

We generally separate dependency bumps and functionality in PRs.

**Comment by inge4pres** [comment]
Hi @jacobbednarz yes I'll revert those in the branch

**Comment by jacobbednarz** [comment]
@inge4pres We've pulled in the cloudflare-go changes so you should be able to merge the latest master now and have this build as expected.

**Comment by inge4pres** [comment]
rebased master onto the forked branch should be ok to merge now

**Comment by jacobbednarz** [comment]
It looks like you've pulled in all the commit history from the upstream in your branch. Are you able to just include your changes?

**Comment by inge4pres** [comment]
Yeah I kind of messed up with this PR... closing and re-opening a fresh one

**Comment by inge4pres** [comment]
raised #509

**Pull request closed without merging**
