### PR TITLE
Page Rules bugfix / enhancements

### PR DESCRIPTION
**Pull request by SteveGoldthorpe-Work**
Fixes issues:
* BugFix: rules status uses disabled not paused #60 
* Enhancements: Page Rule - Host Header Override #46 (and Bypass Cache on Cookie and Resolve Override).

### CODE REVIEW

**Comment by meirf** [comment]
@prdonahue @catsby please take a look.
There are a bunch of commits here but in total the change is quite small.
(My team can't move forward using terraform without some of these page rules.)
Thank you!

**Comment by leandrocostam** [comment]
We are migrating our DNS provider from Route53 to Cloudflare. We are using terraform for that, but I faced some limitation related to S3 buckets once we have custom names for these buckets. Host_header_override is missing in the currect version of Cloudflare provider. We look forward to see this merged.

**Comment by simpsora** [comment]
We're also using the changes in this PR (along with some in #68) to start managing our page rules as code, and looking forward to seeing it merged.

**Comment by meirf** [comment]
@leandrocostam @simpsora I've put in a request to cloudflare support to make this higher priority for them. I encourage y'all to do the same so they have official data in their system of this customer demand.

**Comment by SteveGoldthorpe-Work** [comment]
I've been in contact with Cloudflare's Product Manager for Terraform and they are fully aware of the issues and are currently working on getting development resources the relevant access.  This all sounds encouraging.

**Comment by simpsora** [comment]
@SteveGoldthorpe-Work some of this has already been merged as part of https://github.com/terraform-providers/terraform-provider-cloudflare/pull/76 -- specifically `bypass_cache_on_cookie`, `host_header_override`, and `resolve_override`.

The other two changes (addition of `waf` and `s/paused/disabled/` are still useful and not present in master.  There's someone actively working on this repo now, so hopefully it'll get some traction!

**Comment by simpsora** [comment]
Opened a couple of new PRs:

- https://github.com/terraform-providers/terraform-provider-cloudflare/pull/84 fixes the `disabled` status
- https://github.com/terraform-providers/terraform-provider-cloudflare/pull/85 adds `waf`

**Pull request closed without merging**
