### PR TITLE
Support 0.12

### PR DESCRIPTION
**Pull request by jacobbednarz**
Puts all the building blocks in place for adding 0.12 support.

- [x] Get provider building and working as intended
- [x] Update tests to use 0.12 syntax
- [x] Ensure CI is green for acceptance tests
- [x] Update README to reference new Go + Terraform minimum versions

### CODE REVIEW

**Comment by jacobbednarz** [comment]
Using the following example setup, this branch is working as expected.

```hcl
provider "cloudflare" {
  email  = "${var.cloudflare_email}"
  token  = "${var.cloudflare_token}"
  org_id = "${var.org_id}"
}

resource "cloudflare_record" "foobar" {
  domain = "${var.cloudflare_domain}"
  name   = "test"
  value  = "example.com"
  type   = "CNAME"
  ttl    = 120
}
```

**Comment by jacobbednarz** [comment]
This really isn't ready for review just yet but when things are in "draft", the branch isn't visible to external systems so things like CI aren't triggered.

**Comment by jacobbednarz** [comment]
Integration tests for CI are all green with the exception of those three flakey ones which need the sweeper (addressed in #321).

**Comment by mgkeen** [comment]
v0.12 went live like an hour ago. go go go! 😉 Anything I can do to help?

**Comment by jacobbednarz** [comment]
Release to be cut in next couple of days once the dust has settled for the Hashicorp folks. In the meantime, feel free to build against `master`.

**Comment by rafilkmp3** [comment]
@jacobbednarz  how i can build and use ?

**Comment by jacobbednarz** [comment]
Please see the [building the provider ](https://github.com/terraform-providers/terraform-provider-cloudflare#building-the-provider)section of the README.

**Comment by jacobbednarz** [comment]
1.15.0 was released today with 0.12 compatibility.

**Pull request merged**
